name = "resell-api"
main = "worker.mjs"
compatibility_date = "2024-12-01"

[vars]
# ALLOWED_ORIGIN is a plain var; OWNER_TOKEN is a secret set via wrangler secret put
ALLOWED_ORIGIN = "https://ebay-resell-ui.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "resellapp"
