name: Nightly D1 Backup to GitHub Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "12 7 * * *" # 07:12 UTC daily

permissions:
  contents: write

env:
  D1_NAME: resellapp

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Wrangler
        run: npm i -g wrangler@4

      - name: Verify Cloudflare API access
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          set -euo pipefail
          curl -s -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/d1/database" \
            | jq -e '.success == true' >/dev/null

      - name: Export D1 -> SQL
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          set -euo pipefail
          wrangler --version
          wrangler d1 export "$D1_NAME" --remote > d1-backup.sql
          if ! grep -Eq '(CREATE TABLE|BEGIN TRANSACTION|PRAGMA)' d1-backup.sql; then
            echo "SQL dump looks empty/suspicious"; exit 1
          fi
          gzip -9 d1-backup.sql
          ls -lh d1-backup.sql.gz

      - name: Publish GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          TAG="d1-backup-$(date -u +'%Y%m%d-%H%M%S')"
          gh release create "$TAG" d1-backup.sql.gz \
            --title "$TAG" --generate-notes --latest=false
