name: Nightly D1 Backup to GitHub Releases

on:
  schedule:
    - cron: '17 5 * * *'   # daily at 05:17 UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to create Releases and upload assets
      actions: read
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      D1_NAME: resellapp
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm i -g wrangler@3

      - name: Dump D1 database (SQLite .dump)
        run: |
          set -euo pipefail
          wrangler d1 execute "$D1_NAME" --remote --account-id "$CLOUDFLARE_ACCOUNT_ID" --command '.dump' > d1-backup.sql
          ls -l d1-backup.sql
          # Quick sanity check
          grep -q 'CREATE TABLE' d1-backup.sql || { echo "Backup file looks suspicious (no CREATE TABLE)."; exit 1; }

      - name: Create GitHub Release and upload dump
        run: |
          set -euo pipefail
          TAG="d1-backup-$(date -u +%Y%m%dT%H%M%SZ)"
          echo "Creating release ${TAG}"
          gh release create "$TAG" --title "$TAG" --notes "Automated D1 dump (resellapp)" d1-backup.sql
