name: Nightly D1 Backup to GitHub Releases

on:
  schedule:
    - cron: "17 5 * * *"   # daily at ~05:17 UTC
  workflow_dispatch:

permissions:
  contents: write   # needed to create releases & upload assets

env:
  D1_NAME: resellapp

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Wrangler
        run: npm i -g wrangler@4

      - name: Dump D1 database (SQLite .dump)
        shell: bash
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          D1_NAME: ${{ env.D1_NAME }}
        run: |
          set -euo pipefail
          # Prefer wrangler d1 export if available (wrangler@4)
          if wrangler d1 export "$D1_NAME" --remote --output d1-backup.sql; then
            :
          else
            # Fallback to .dump if export is unavailable
            wrangler d1 execute "$D1_NAME" --remote --command '.dump' > d1-backup.sql
          fi
          ls -l d1-backup.sql
          grep -q 'CREATE TABLE' d1-backup.sql || { echo "Backup file looks suspicious (no CREATE TABLE)."; exit 1; }

      - name: Compress backup
        run: gzip -9 d1-backup.sql

      - name: Create release & upload asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          TS="$(date -u +'%Y-%m-%dT%H%MZ')"
          TAG="d1-backup-${TS}"
          TITLE="$TAG"
          NOTES="Automated D1 backup from GitHub Actions (wrangler@4)."
          gh release create "$TAG" --title "$TITLE" --notes "$NOTES" d1-backup.sql.gz
