name: Nightly D1 Backup to GitHub Releases

on:
  workflow_dispatch:
  schedule:
    - cron: '17 5 * * *' # Daily at 05:17 UTC

permissions:
  contents: write

jobs:
  backup:
    name: Export D1 -> GitHub Release
    runs-on: ubuntu-latest
    env:
      D1_NAME: resellapp
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install wrangler
        run: npm i -g wrangler@4

      - name: Export D1 (remote)
        run: |
          set -euxo pipefail
          wrangler d1 export "$D1_NAME" --remote --account-id "$CLOUDFLARE_ACCOUNT_ID" --output d1-export.sql
          ls -l d1-export.sql
          gzip -9 d1-export.sql
          ls -l d1-export.sql.gz

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: d1-backup-${{ github.run_id }}
          name: D1 Backup ${{ github.run_id }}
          body: |
            Automated D1 export from workflow run ${{ github.run_id }} at ${{ github.run_started_at }}.
            Database: ${{ env.D1_NAME }}.
          files: d1-export.sql.gz
