name: Nightly D1 Backup to GitHub Releases

on:
  schedule:
    - cron: '17 5 * * *'   # nightly at 05:17 UTC
  workflow_dispatch: {}

permissions:
  contents: write   # needed to create Releases & upload assets

jobs:
  backup:
    runs-on: ubuntu-latest
    concurrency:
      group: d1-backup
      cancel-in-progress: false
    env:
      D1_NAME: resellapp
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Wrangler (v4)
        run: npm i -g wrangler@4

      - name: Dump D1 database (SQLite export)
        run: |
          set -euo pipefail
          wrangler d1 export "$D1_NAME" --remote --output d1-backup.sql
          ls -l d1-backup.sql
          # quick sanity check: must contain at least one CREATE TABLE
          grep -q 'CREATE TABLE' d1-backup.sql || { echo "Backup file looks suspicious (no CREATE TABLE)."; exit 1; }

      - name: Compress backup
        run: gzip -9 d1-backup.sql

      - name: Create GitHub Release & upload asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          TAG="d1-backup-$(date -u +%Y%m%d-%H%M%S)"
          TITLE="D1 backup ($D1_NAME) $(date -u +'%F %T UTC')"
          NOTES="Automated D1 backup created by GitHub Actions (wrangler d1 export + gzip)."
          gh release create "$TAG" d1-backup.sql.gz --title "$TITLE" --notes "$NOTES" -R "$GITHUB_REPOSITORY"
