name: Nightly D1 Backup to GitHub Releases
on:
  workflow_dispatch:
  schedule:
    - cron: "17 5 * * *"   # 05:17 UTC daily
permissions:
  contents: write
jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      D1_NAME: resellapp
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Wrangler
        run: npm i -g wrangler@4

      - name: Dump D1 database (.dump -> gzip)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          set -euo pipefail
          # Export with wrangler v4 (no --account-id flag needed when using token)
          wrangler d1 execute "$D1_NAME" --remote --command '.dump' > d1-backup.sql
          ls -l d1-backup.sql
          # Basic sanity check
          grep -q 'CREATE TABLE' d1-backup.sql || { echo "Backup file looks suspicious (no CREATE TABLE)."; exit 1; }
          gzip -f d1-backup.sql
          ls -l d1-backup.sql.gz

      - name: Create Release & Upload Asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          TAG="d1-backup-$(date -u +%Y%m%d-%H%M%SZ)"
          gh release create "$TAG" --notes "Automated nightly D1 backup" || true
          gh release upload "$TAG" d1-backup.sql.gz --clobber
