name: Deploy Cloudflare Pages
on:
  push:
    branches: [ "main" ]
    paths:
      - "ui/**"
      - ".github/workflows/pages-deploy.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install deps & build UI
        working-directory: ui
        run: |
          npm ci --prefer-offline || npm install
          npm run build
      - run: npm i -g wrangler
      - name: Deploy to Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler pages project create ebay-resell-ui --production-branch=main || true
          wrangler pages deploy ui/dist --project-name=ebay-resell-ui --branch=main --commit-dirty=true
